"""del necessity of tg id

Revision ID: 17852aec8cad
Revises: e1d8fd972b61
Create Date: 2022-07-10 01:51:09.506143

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '17852aec8cad'
down_revision = 'e1d8fd972b61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_tg_id', table_name='student')
    op.create_index(op.f('ix_student_tg_id'), 'student', ['tg_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_tg_id'), table_name='student')
    op.create_index('ix_student_tg_id', 'student', ['tg_id'], unique=False)
    # ### end Alembic commands ###
