"""add is_bot flag for user

Revision ID: 4778b1eb9cb8
Revises: b4ff943a7d78
Create Date: 2022-07-09 10:41:03.463447

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4778b1eb9cb8'
down_revision = 'b4ff943a7d78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_bot', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_bot')
    # ### end Alembic commands ###
