"""add one to one student-user connection

Revision ID: e1d8fd972b61
Revises: 4778b1eb9cb8
Create Date: 2022-07-09 22:46:20.631627

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e1d8fd972b61'
down_revision = '4778b1eb9cb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'student', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    op.drop_column('student', 'user_id')
    # ### end Alembic commands ###
