"""add student to tag

Revision ID: f1e1d648aeff
Revises: 3debd41271eb
Create Date: 2022-07-08 03:21:38.818083

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'f1e1d648aeff'
down_revision = '3debd41271eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'tag', 'student', ['student_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_column('tag', 'student_id')
    # ### end Alembic commands ###
